 -
   hosts: all
   vars:
       db_user: sanjay
       db_name: student
       db_password: Dfuse912
   tasks:
    - name: Install dependencies for PostgreSQL
      yum: name={{ item }} update_cache=true state=latest
      with_items:
        - bash
        - openssl
        - libssl-dev
        - libssl-doc
    - name: Install PostgreSQL 
      yum: name={{ item }} update_cache=true state=present
      with_items:
        - postgresql
        - postgresql-contrib
        - libpq-dev
        - python3-psycopg2
    - name: Ensure the PostgreSQL service is running
      service: name=postgresql state=started enabled=yes
    - name: Create the database specified in vars
      become: true
      become_user: postgres
      postgresql_db: name={{ db_name }}
        template='template0'
        state=present
    - name: Ensure user has access to the new database
      become: true
      become_user: postgres
      postgresql_user: db={{ db_name }}
        name={{ db_user }}
        password={{ db_password }}
        priv=ALL
        state=present
    - name: Ensure user does not have unnecessary permissions
      become: true
      become_user: postgres
      postgresql_user: name={{ db_user }}
        role_attr_flags=NOSUPERUSER,NOCREATEDB
        state=present        
    - name: Add some dummy data to our database
      become: true
      become_user: postgres
      shell: psql {{ db_name }} < /tmp/dump.sql        