- 
  name: pb on use case of loops
  hosts: all
  tasks:
    - name: below is loop for yum intializations
      yum:
        name: "{{ item }}"
        state: absent
      with_items:
      - git
      - docker