-
  name: playone
  hosts: all
  tasks: 
    - name: code to create a directory
      file:
        path: /root/sample_maveen_project/lib
        state: directory
    - name: Copying files from source to destination
      become: true
      copy: 
        src: /home/sanjay/jenkins/workspace/sample_maveen_project/webapp/target/webapp.war
        dest: /root/sample_maveen_project/lib     
