-
  name: playone1
  hosts: all
  tasks: 
    - name: code to create a directory
      file:
        path: /root/sample_maveen_project/lib
        state: directory
    - name: Copying jar file from source to destination
      become: true
      copy: 
        src: /home/sanjay/jenkins/workspace/sample_maveen_project/webapp/target/webapp.war
        dest: /root/sample_maveen_project/lib     
        owner: root
        group: root        
        mode: 0644
    - name: copying config file
      become: true
      copy: 
        src: /home/sanjay/jenkins/workspace/sample_maveen_project/Jenkinsfile
        dest: /root/sample_maveen_project/lib
    - name: "Upload file into Hadoop/hdfs cluster"
      command: "hadoop fs -put /root/sample_maveen_project/lib/*.* /sample_project/"
      register: data
      ignore_errors: yes